export const bemMap = {
  "app-about-page__c1": "space-y-12 pb-16 pt-12",
  "app-about-page__c10": "text-lg font-bold text-white",
  "app-about-page__c11": "mt-2 text-zinc-400",
  "app-about-page__c2": "grid gap-5 md:grid-cols-3",
  "app-about-page__c3": "surface-panel p-6",
  "app-about-page__c4": "text-lg font-bold text-white",
  "app-about-page__c5": "mt-2 text-zinc-400",
  "app-about-page__c6": "surface-panel p-6",
  "app-about-page__c7": "text-lg font-bold text-white",
  "app-about-page__c8": "mt-2 text-zinc-400",
  "app-about-page__c9": "surface-panel p-6",
  "app-blog-loading__c1": "space-y-10 pb-16 pt-12",
  "app-blog-loading__c10": "space-y-3 md:col-span-7",
  "app-blog-loading__c11": "theme-skeleton h-5 w-36 rounded-lg",
  "app-blog-loading__c12": "theme-skeleton h-10 w-full rounded-xl",
  "app-blog-loading__c13": "theme-skeleton h-20 w-full rounded-xl",
  "app-blog-loading__c14": "theme-skeleton h-10 w-36 rounded-full",
  "app-blog-loading__c15": "grid gap-5 md:grid-cols-12",
  "app-blog-loading__c16": "theme-skeleton h-64 rounded-2xl md:col-span-5 md:order-2",
  "app-blog-loading__c17": "space-y-3 md:col-span-7 md:order-1",
  "app-blog-loading__c18": "theme-skeleton h-5 w-36 rounded-lg",
  "app-blog-loading__c19": "theme-skeleton h-10 w-full rounded-xl",
  "app-blog-loading__c2": "space-y-4",
  "app-blog-loading__c20": "theme-skeleton h-20 w-full rounded-xl",
  "app-blog-loading__c21": "theme-skeleton h-10 w-36 rounded-full",
  "app-blog-loading__c3": "theme-skeleton h-7 w-28 rounded-full",
  "app-blog-loading__c4": "theme-skeleton h-14 w-full max-w-3xl rounded-2xl",
  "app-blog-loading__c5": "theme-skeleton h-6 w-full max-w-2xl rounded-xl",
  "app-blog-loading__c6": "theme-skeleton h-16 w-full rounded-2xl",
  "app-blog-loading__c7": "space-y-10",
  "app-blog-loading__c8": "grid gap-5 md:grid-cols-12",
  "app-blog-loading__c9": "theme-skeleton h-64 rounded-2xl md:col-span-5",
  "app-blog-page__c1": "space-y-10 pb-16 pt-12",
  "app-blog-page__c10": "h-64 w-full object-cover transition duration-500 group-hover:scale-[1.03]",
  "app-blog-page__c11": "text-xs tracking-[0.2em] text-zinc-400",
  "app-blog-page__c12": "mt-2 text-3xl font-bold text-white",
  "app-blog-page__c13": "mt-3 max-w-2xl text-zinc-400",
  "app-blog-page__c14": "premium-btn premium-btn-secondary premium-control mt-5",
  "app-blog-page__c15": "group relative overflow-hidden md:col-span-5",
  "app-blog-page__c16": "md:order-1",
  "app-blog-page__c17": "md:order-2",
  "app-blog-page__c18": "md:col-span-7",
  "app-blog-page__c19": "md:order-2",
  "app-blog-page__c2": "surface-rail flex gap-3 p-4",
  "app-blog-page__c20": "md:order-1",
  "app-blog-page__c3": "premium-input",
  "app-blog-page__c4": "premium-btn premium-btn-primary premium-control shrink-0 text-white",
  "app-blog-page__c5": "theme-empty-state surface-panel p-8 text-center",
  "app-blog-page__c6": "theme-heading text-2xl font-bold",
  "app-blog-page__c7": "theme-muted mt-3",
  "app-blog-page__c8": "space-y-12",
  "app-blog-page__c9": "grid items-center gap-5 md:grid-cols-12",
  "app-blog-slug-page__c1": "max-w-5xl space-y-8 pb-16 pt-12 motion-rise",
  "app-blog-slug-page__c2": "grid gap-6 md:grid-cols-12",
  "app-blog-slug-page__c3": "md:col-span-8",
  "app-blog-slug-page__c4": "text-xs tracking-[0.24em] text-zinc-400",
  "app-blog-slug-page__c5": "mt-2 text-4xl font-black text-white md:text-5xl",
  "app-blog-slug-page__c6": "h-72 w-full object-cover md:h-[28rem]",
  "app-blog-slug-page__c7": "editorial-article max-w-3xl text-lg",
  "app-contact-page__c1": "space-y-10 pb-16 pt-12",
  "app-contact-page__c2": "max-w-xl",
  "app-dashboard-blog-page__c1": "space-y-4",
  "app-dashboard-blog-page__c2": "surface-rail p-5",
  "app-dashboard-blog-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-dashboard-blog-page__c4": "mt-2 text-3xl font-black text-white",
  "app-dashboard-blog-page__c5": "surface-rail flex gap-3 p-4",
  "app-dashboard-blog-page__c6": "premium-input",
  "app-dashboard-blog-page__c7": "premium-btn premium-btn-primary premium-control shrink-0 text-white",
  "app-dashboard-contacts-page__c1": "space-y-4",
  "app-dashboard-contacts-page__c2": "surface-rail p-5",
  "app-dashboard-contacts-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-dashboard-contacts-page__c4": "mt-2 text-3xl font-black text-white",
  "app-dashboard-interests-page__c1": "space-y-4",
  "app-dashboard-interests-page__c2": "surface-rail p-5",
  "app-dashboard-interests-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-dashboard-interests-page__c4": "mt-2 text-3xl font-black text-white",
  "app-dashboard-layout__c1": "grid gap-6 py-10 md:grid-cols-[260px_1fr]",
  "app-dashboard-layout__c2": "surface-panel h-fit p-4",
  "app-dashboard-layout__c3": "mb-2 text-xs font-semibold tracking-[0.24em] text-zinc-400",
  "app-dashboard-layout__c4": "mb-5 font-mono text-lg text-purple-300",
  "app-dashboard-layout__c5": "space-y-2",
  "app-dashboard-layout__c6": "premium-control block border border-transparent px-3 py-2 text-sm font-semibold text-zinc-400 hover:border-purple-500/50 hover:bg-slate-900/60 hover:text-purple-300",
  "app-dashboard-layout__c7": "space-y-5",
  "app-dashboard-news-page__c1": "space-y-4",
  "app-dashboard-news-page__c2": "surface-rail p-5",
  "app-dashboard-news-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-dashboard-news-page__c4": "mt-2 text-3xl font-black text-white",
  "app-dashboard-news-page__c5": "surface-rail flex gap-3 p-4",
  "app-dashboard-news-page__c6": "premium-input",
  "app-dashboard-news-page__c7": "premium-btn premium-btn-primary premium-control shrink-0 text-white",
  "app-dashboard-page__c1": "space-y-6",
  "app-dashboard-page__c10": "text-xs tracking-[0.2em] text-zinc-400",
  "app-dashboard-page__c11": "mt-2 text-3xl font-black text-white",
  "app-dashboard-page__c12": "text-xs tracking-[0.2em] text-zinc-400",
  "app-dashboard-page__c13": "mt-2 text-3xl font-black text-purple-300",
  "app-dashboard-page__c14": "text-xs tracking-[0.2em] text-zinc-400",
  "app-dashboard-page__c15": "mt-2 text-3xl font-black text-purple-300",
  "app-dashboard-page__c2": "surface-rail p-5",
  "app-dashboard-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-dashboard-page__c4": "mt-2 text-3xl font-black text-white",
  "app-dashboard-page__c5": "grid gap-4 sm:grid-cols-2 lg:grid-cols-3",
  "app-dashboard-page__c6": "text-xs tracking-[0.2em] text-zinc-400",
  "app-dashboard-page__c7": "mt-2 text-3xl font-black text-white",
  "app-dashboard-page__c8": "text-xs tracking-[0.2em] text-zinc-400",
  "app-dashboard-page__c9": "mt-2 text-3xl font-black text-white",
  "app-dashboard-projects-page__c1": "space-y-4",
  "app-dashboard-projects-page__c2": "surface-rail p-5",
  "app-dashboard-projects-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-dashboard-projects-page__c4": "mt-2 text-3xl font-black text-white",
  "app-dashboard-projects-page__c5": "surface-rail flex gap-3 p-4",
  "app-dashboard-projects-page__c6": "premium-input",
  "app-dashboard-projects-page__c7": "premium-btn premium-btn-primary premium-control shrink-0 text-white",
  "app-dashboard-site-content-page__c1": "space-y-4",
  "app-dashboard-site-content-page__c2": "surface-rail p-5",
  "app-dashboard-site-content-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-dashboard-site-content-page__c4": "mt-2 text-3xl font-black text-white",
  "app-layout__c1": "relative z-10",
  "app-layout__c2": "antialiased",
  "app-login-page__c1": "flex min-h-[70vh] items-center justify-center py-12",
  "app-login-page__c2": "w-full max-w-md space-y-4",
  "app-login-page__c3": "text-center text-3xl font-black text-white",
  "app-login-page__c4": "text-center text-sm text-zinc-400",
  "app-login-page__c5": "premium-control font-semibold text-purple-300 hover:text-purple-200",
  "app-news-loading__c1": "space-y-10 pb-16 pt-12",
  "app-news-loading__c10": "theme-skeleton h-44 w-full rounded-2xl",
  "app-news-loading__c2": "space-y-4",
  "app-news-loading__c3": "theme-skeleton h-7 w-28 rounded-full",
  "app-news-loading__c4": "theme-skeleton h-14 w-full max-w-3xl rounded-2xl",
  "app-news-loading__c5": "theme-skeleton h-6 w-full max-w-2xl rounded-xl",
  "app-news-loading__c6": "theme-skeleton h-16 w-full rounded-2xl",
  "app-news-loading__c7": "space-y-5",
  "app-news-loading__c8": "theme-skeleton h-44 w-full rounded-2xl",
  "app-news-loading__c9": "theme-skeleton h-44 w-full rounded-2xl",
  "app-news-page__c1": "space-y-10 pb-16 pt-12",
  "app-news-page__c10": "text-xs tracking-[0.2em] text-zinc-400",
  "app-news-page__c11": "mt-2 text-2xl font-bold text-white",
  "app-news-page__c12": "mt-3 text-zinc-400",
  "app-news-page__c13": "premium-btn premium-btn-secondary premium-control mt-5",
  "app-news-page__c2": "surface-rail flex gap-3 p-4",
  "app-news-page__c3": "premium-input",
  "app-news-page__c4": "premium-btn premium-btn-primary premium-control shrink-0 text-white",
  "app-news-page__c5": "theme-empty-state surface-panel p-8 text-center",
  "app-news-page__c6": "theme-heading text-2xl font-bold",
  "app-news-page__c7": "theme-muted mt-3",
  "app-news-page__c8": "space-y-5",
  "app-news-page__c9": "surface-panel motion-rise p-6",
  "app-news-slug-page__c1": "max-w-5xl space-y-8 pb-16 pt-12 motion-rise",
  "app-news-slug-page__c2": "text-xs tracking-[0.24em] text-zinc-400",
  "app-news-slug-page__c3": "mt-2 max-w-4xl text-4xl font-black text-white md:text-5xl",
  "app-news-slug-page__c4": "section-divider",
  "app-news-slug-page__c5": "editorial-article max-w-3xl text-lg",
  "app-page__c1": "space-y-[var(--space-section)] pb-16 pt-10",
  "app-page__c10": "md:col-span-3",
  "app-page__c11": "text-xs tracking-[0.2em] text-zinc-400",
  "app-page__c12": "mt-2 text-3xl font-black text-purple-300",
  "app-page__c13": "text-sm text-zinc-400",
  "app-page__c14": "md:col-span-4",
  "app-page__c15": "text-xs tracking-[0.2em] text-zinc-400",
  "app-page__c16": "mt-2 text-3xl font-black text-purple-300",
  "app-page__c17": "mt-2 text-sm text-zinc-400",
  "app-page__c18": "surface-panel grid gap-7 p-6 md:grid-cols-[1.2fr_0.8fr] md:p-8",
  "app-page__c19": "text-xs tracking-[0.22em] text-zinc-400",
  "app-page__c2": "mx-auto w-[99vw] px-1 sm:px-2 lg:px-3",
  "app-page__c20": "mt-3 text-3xl font-bold text-white",
  "app-page__c21": "mt-3 max-w-2xl text-zinc-400",
  "app-page__c22": "space-y-2 text-sm",
  "app-page__c23": "data-strip flex items-center justify-between gap-3",
  "app-page__c24": "font-semibold text-white",
  "app-page__c25": "font-mono text-xs text-purple-300",
  "app-page__c3": "space-y-8",
  "app-page__c4": "surface-rail grid gap-2 px-4 py-3 text-xs tracking-[0.16em] text-zinc-400 sm:grid-cols-3",
  "app-page__c5": "grid gap-5 md:grid-cols-12",
  "app-page__c6": "md:col-span-5",
  "app-page__c7": "text-xs tracking-[0.2em] text-zinc-400",
  "app-page__c8": "mt-2 text-4xl font-black text-white",
  "app-page__c9": "mt-4 text-zinc-400",
  "app-projects-loading__c1": "space-y-10 pb-16 pt-12",
  "app-projects-loading__c10": "theme-skeleton h-[22rem] rounded-2xl md:col-span-6",
  "app-projects-loading__c11": "theme-skeleton h-[22rem] rounded-2xl md:col-span-6",
  "app-projects-loading__c2": "space-y-4",
  "app-projects-loading__c3": "theme-skeleton h-7 w-32 rounded-full",
  "app-projects-loading__c4": "theme-skeleton h-14 w-full max-w-3xl rounded-2xl",
  "app-projects-loading__c5": "theme-skeleton h-6 w-full max-w-2xl rounded-xl",
  "app-projects-loading__c6": "theme-skeleton h-16 w-full rounded-2xl",
  "app-projects-loading__c7": "grid gap-5 md:grid-cols-12",
  "app-projects-loading__c8": "theme-skeleton h-[22rem] rounded-2xl md:col-span-6",
  "app-projects-loading__c9": "theme-skeleton h-[22rem] rounded-2xl md:col-span-6",
  "app-projects-page__c1": "space-y-10 pb-16 pt-12",
  "app-projects-page__c10": "h-52 w-full object-cover",
  "app-projects-page__c11": "mt-4 flex items-start justify-between gap-3",
  "app-projects-page__c12": "text-xl font-bold text-white",
  "app-projects-page__c13": "font-mono text-xs tracking-[0.22em] text-purple-300",
  "app-projects-page__c14": "mt-2 text-zinc-400",
  "app-projects-page__c15": "mt-4 flex flex-wrap gap-2 text-xs",
  "app-projects-page__c16": "data-strip",
  "app-projects-page__c17": "data-strip",
  "app-projects-page__c18": "premium-btn premium-btn-ghost premium-control mt-5",
  "app-projects-page__c2": "surface-rail flex gap-3 p-4",
  "app-projects-page__c3": "premium-input",
  "app-projects-page__c4": "premium-btn premium-btn-primary premium-control shrink-0 text-white",
  "app-projects-page__c5": "theme-empty-state surface-panel p-8 text-center",
  "app-projects-page__c6": "theme-heading text-2xl font-bold",
  "app-projects-page__c7": "theme-muted mt-3",
  "app-projects-page__c8": "grid gap-5 md:grid-cols-12",
  "app-projects-page__c9": "surface-panel motion-rise p-5 md:col-span-6",
  "app-projects-slug-page__c1": "space-y-8 pb-16 pt-12",
  "app-projects-slug-page__c10": "mt-4 space-y-2 text-sm text-zinc-400",
  "app-projects-slug-page__c11": "data-strip flex items-center justify-between gap-2",
  "app-projects-slug-page__c12": "font-semibold text-white",
  "app-projects-slug-page__c13": "font-mono text-purple-300",
  "app-projects-slug-page__c14": "surface-panel p-6",
  "app-projects-slug-page__c15": "text-xl font-bold text-white",
  "app-projects-slug-page__c16": "mt-4 space-y-2 text-sm text-zinc-400",
  "app-projects-slug-page__c17": "data-strip flex items-center justify-between gap-2",
  "app-projects-slug-page__c18": "font-semibold text-white",
  "app-projects-slug-page__c19": "font-mono text-purple-300",
  "app-projects-slug-page__c2": "surface-panel p-8 motion-rise",
  "app-projects-slug-page__c20": "max-w-xl",
  "app-projects-slug-page__c3": "text-xs tracking-[0.24em] text-zinc-400",
  "app-projects-slug-page__c4": "mt-3 text-4xl font-black text-white",
  "app-projects-slug-page__c5": "mt-4 max-w-4xl text-zinc-400",
  "app-projects-slug-page__c6": "mt-5 h-64 w-full object-cover",
  "app-projects-slug-page__c7": "grid gap-5 md:grid-cols-2",
  "app-projects-slug-page__c8": "surface-panel p-6",
  "app-projects-slug-page__c9": "text-xl font-bold text-white",
  "app-services-page__c1": "space-y-12 pb-16 pt-12",
  "app-services-page__c2": "grid gap-5 md:grid-cols-2",
  "app-services-page__c3": "surface-panel p-6",
  "app-services-page__c4": "text-xl font-bold text-white",
  "app-services-page__c5": "mt-2 text-zinc-400",
  "app-signup-page__c1": "flex min-h-[70vh] items-center justify-center py-12",
  "app-signup-page__c2": "w-full max-w-md space-y-4",
  "app-signup-page__c3": "text-center text-3xl font-black text-white",
  "app-signup-page__c4": "text-center text-sm text-zinc-400",
  "components-dashboard-blog-manager__c1": "space-y-6",
  "components-dashboard-blog-manager__c10": "mt-3 flex gap-2",
  "components-dashboard-blog-manager__c11": "premium-btn premium-btn-secondary premium-control text-sm",
  "components-dashboard-blog-manager__c12": "premium-btn premium-control border-rose-400/70 bg-rose-500/20 text-sm text-rose-200",
  "components-dashboard-blog-manager__c2": "surface-panel space-y-3 p-5",
  "components-dashboard-blog-manager__c3": "premium-input",
  "components-dashboard-blog-manager__c4": "premium-btn premium-btn-primary premium-control text-white",
  "components-dashboard-blog-manager__c5": "text-sm text-zinc-400",
  "components-dashboard-blog-manager__c6": "space-y-3",
  "components-dashboard-blog-manager__c7": "surface-panel p-4",
  "components-dashboard-blog-manager__c8": "text-lg font-bold text-white",
  "components-dashboard-blog-manager__c9": "mt-1 text-sm text-zinc-400",
  "components-dashboard-contact-submissions-table__c1": "overflow-hidden border border-purple-500/40 bg-slate-950/60",
  "components-dashboard-contact-submissions-table__c10": "px-4 py-3 text-white",
  "components-dashboard-contact-submissions-table__c11": "px-4 py-3",
  "components-dashboard-contact-submissions-table__c12": "px-4 py-3",
  "components-dashboard-contact-submissions-table__c13": "px-4 py-3 text-zinc-300",
  "components-dashboard-contact-submissions-table__c14": "px-4 py-3 text-zinc-400",
  "components-dashboard-contact-submissions-table__c2": "w-full text-left text-sm",
  "components-dashboard-contact-submissions-table__c3": "bg-slate-900 text-zinc-400",
  "components-dashboard-contact-submissions-table__c4": "px-4 py-3",
  "components-dashboard-contact-submissions-table__c5": "px-4 py-3",
  "components-dashboard-contact-submissions-table__c6": "px-4 py-3",
  "components-dashboard-contact-submissions-table__c7": "px-4 py-3",
  "components-dashboard-contact-submissions-table__c8": "px-4 py-3",
  "components-dashboard-contact-submissions-table__c9": "border-t border-purple-600/55 text-zinc-400",
  "components-dashboard-news-manager__c1": "space-y-6",
  "components-dashboard-news-manager__c10": "mt-3 flex gap-2",
  "components-dashboard-news-manager__c11": "premium-btn premium-btn-secondary premium-control text-sm",
  "components-dashboard-news-manager__c12": "premium-btn premium-control border-rose-400/70 bg-rose-500/20 text-sm text-rose-200",
  "components-dashboard-news-manager__c2": "surface-panel space-y-3 p-5",
  "components-dashboard-news-manager__c3": "premium-input",
  "components-dashboard-news-manager__c4": "premium-btn premium-btn-primary premium-control text-white",
  "components-dashboard-news-manager__c5": "text-sm text-zinc-400",
  "components-dashboard-news-manager__c6": "space-y-3",
  "components-dashboard-news-manager__c7": "surface-panel p-4",
  "components-dashboard-news-manager__c8": "text-lg font-bold text-white",
  "components-dashboard-news-manager__c9": "mt-1 text-sm text-zinc-400",
  "components-dashboard-project-interests-table__c1": "overflow-hidden border border-purple-500/40 bg-slate-950/60",
  "components-dashboard-project-interests-table__c10": "px-4 py-3",
  "components-dashboard-project-interests-table__c11": "px-4 py-3 text-purple-300",
  "components-dashboard-project-interests-table__c12": "px-4 py-3 text-zinc-400",
  "components-dashboard-project-interests-table__c2": "w-full text-left text-sm",
  "components-dashboard-project-interests-table__c3": "bg-slate-900 text-zinc-400",
  "components-dashboard-project-interests-table__c4": "px-4 py-3",
  "components-dashboard-project-interests-table__c5": "px-4 py-3",
  "components-dashboard-project-interests-table__c6": "px-4 py-3",
  "components-dashboard-project-interests-table__c7": "px-4 py-3",
  "components-dashboard-project-interests-table__c8": "border-t border-purple-600/55 text-zinc-400",
  "components-dashboard-project-interests-table__c9": "px-4 py-3 text-white",
  "components-dashboard-project-manager__c1": "space-y-6",
  "components-dashboard-project-manager__c10": "space-y-3",
  "components-dashboard-project-manager__c11": "surface-panel p-4 motion-rise",
  "components-dashboard-project-manager__c12": "text-lg font-bold text-white",
  "components-dashboard-project-manager__c13": "mt-1 text-sm text-zinc-400",
  "components-dashboard-project-manager__c14": "mt-3 flex gap-2",
  "components-dashboard-project-manager__c15": "premium-btn premium-btn-secondary premium-control text-sm",
  "components-dashboard-project-manager__c16": "premium-btn premium-control border-rose-400/70 bg-rose-500/20 text-sm text-rose-200",
  "components-dashboard-project-manager__c2": "surface-panel space-y-3 p-5 motion-rise",
  "components-dashboard-project-manager__c3": "premium-input",
  "components-dashboard-project-manager__c4": "premium-input",
  "components-dashboard-project-manager__c5": "premium-input",
  "components-dashboard-project-manager__c6": "premium-input font-mono text-sm",
  "components-dashboard-project-manager__c7": "premium-input font-mono text-sm",
  "components-dashboard-project-manager__c8": "premium-btn premium-btn-primary premium-control text-white",
  "components-dashboard-project-manager__c9": "text-sm text-zinc-400",
  "components-dashboard-site-content-manager__c1": "space-y-5",
  "components-dashboard-site-content-manager__c2": "surface-panel space-y-3 p-5",
  "components-dashboard-site-content-manager__c3": "text-lg font-bold text-white",
  "components-dashboard-site-content-manager__c4": "premium-input",
  "components-dashboard-site-content-manager__c5": "premium-input",
  "components-dashboard-site-content-manager__c6": "premium-input",
  "components-dashboard-site-content-manager__c7": "premium-input",
  "components-dashboard-site-content-manager__c8": "premium-btn premium-btn-primary premium-control text-white",
  "components-dashboard-site-content-manager__c9": "text-sm text-zinc-400",
  "components-forms-contact-form__c1": "surface-panel space-y-4 p-6",
  "components-forms-contact-form__c2": "premium-input",
  "components-forms-contact-form__c3": "premium-input",
  "components-forms-contact-form__c4": "premium-input",
  "components-forms-contact-form__c5": "space-y-2",
  "components-forms-contact-form__c6": "text-sm font-semibold text-zinc-400",
  "components-forms-contact-form__c7": "premium-input",
  "components-forms-contact-form__c8": "text-sm text-zinc-400",
  "components-forms-contact-form__c9": "premium-btn premium-btn-primary premium-control text-white disabled:opacity-70",
  "components-forms-image-upload-input__c1": "space-y-2",
  "components-forms-image-upload-input__c2": "premium-input",
  "components-forms-image-upload-input__c3": "premium-input",
  "components-forms-image-upload-input__c4": "text-sm text-zinc-400",
  "components-forms-image-upload-input__c5": "text-sm text-zinc-400",
  "components-forms-login-form__c1": "surface-panel space-y-4 p-6",
  "components-forms-login-form__c2": "premium-input",
  "components-forms-login-form__c3": "premium-input",
  "components-forms-login-form__c4": "text-sm text-rose-600",
  "components-forms-login-form__c5": "premium-btn premium-btn-primary premium-control w-full justify-center text-white disabled:opacity-70",
  "components-forms-project-interest-form__c1": "surface-panel space-y-4 p-5",
  "components-forms-project-interest-form__c2": "premium-input",
  "components-forms-project-interest-form__c3": "premium-input",
  "components-forms-project-interest-form__c4": "text-sm text-zinc-400",
  "components-forms-project-interest-form__c5": "premium-btn premium-btn-ghost premium-control disabled:opacity-70",
  "components-forms-rich-text-editor__c1": "space-y-2",
  "components-forms-rich-text-editor__c2": "flex flex-wrap gap-2",
  "components-forms-rich-text-editor__c3": "premium-btn premium-btn-secondary premium-control px-3 py-1 text-sm",
  "components-forms-rich-text-editor__c4": "premium-btn premium-btn-secondary premium-control px-3 py-1 text-sm",
  "components-forms-rich-text-editor__c5": "premium-btn premium-btn-secondary premium-control px-3 py-1 text-sm",
  "components-forms-rich-text-editor__c6": "min-h-40 w-full border border-purple-500/45 bg-slate-950/85 px-3 py-2 text-zinc-300 outline-none focus:border-purple-400",
  "components-forms-signup-form__c1": "surface-panel space-y-4 p-6",
  "components-forms-signup-form__c2": "premium-input",
  "components-forms-signup-form__c3": "premium-input",
  "components-forms-signup-form__c4": "premium-input",
  "components-forms-signup-form__c5": "text-sm text-rose-500",
  "components-forms-signup-form__c6": "text-sm text-purple-300",
  "components-forms-signup-form__c7": "premium-btn premium-btn-primary premium-control w-full justify-center text-white disabled:opacity-70",
  "components-forms-signup-form__c8": "text-center text-sm text-zinc-400",
  "components-forms-signup-form__c9": "premium-control font-semibold text-purple-300 hover:text-purple-200",
  "components-home-hero-slider__c1": "relative overflow-hidden rounded-[26px] border border-purple-500/25 bg-gradient-to-br from-slate-900/95 via-slate-900/80 to-purple-950/55 p-6 shadow-[0_26px_64px_rgba(0,0,0,0.35)] sm:p-10",
  "components-home-hero-slider__c10": "theme-muted max-w-2xl text-base leading-8 sm:text-lg",
  "components-home-hero-slider__c11": "flex flex-wrap gap-3",
  "components-home-hero-slider__c12": "rounded-full border border-purple-300/70 bg-purple-400 px-6 py-3 text-sm font-semibold text-white shadow-[0_10px_26px_rgba(124,58,237,0.35)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-purple-300",
  "components-home-hero-slider__c13": "rounded-full border border-purple-500/65 bg-slate-900/70 px-6 py-3 text-sm font-semibold text-white shadow-[0_8px_20px_rgba(0,0,0,0.28)] transition-all duration-200 hover:-translate-y-0.5 hover:border-purple-300/70",
  "components-home-hero-slider__c14": "grid gap-3 sm:grid-cols-3",
  "components-home-hero-slider__c15": "theme-metric rounded-sm px-4 py-3",
  "components-home-hero-slider__c16": "theme-muted text-xs tracking-[0.2em]",
  "components-home-hero-slider__c17": "theme-heading mt-1 font-mono text-[1.7rem]",
  "components-home-hero-slider__c18": "theme-metric rounded-sm px-4 py-3",
  "components-home-hero-slider__c19": "theme-muted text-xs tracking-[0.2em]",
  "components-home-hero-slider__c2": "pointer-events-none absolute -inset-24 bg-[radial-gradient(circle_at_10%_24%,rgba(124,58,237,0.2),transparent_44%),radial-gradient(circle_at_84%_32%,rgba(167,139,250,0.16),transparent_48%)]",
  "components-home-hero-slider__c20": "theme-heading mt-1 font-mono text-[1.7rem]",
  "components-home-hero-slider__c21": "theme-metric rounded-sm px-4 py-3",
  "components-home-hero-slider__c22": "theme-muted text-xs tracking-[0.2em]",
  "components-home-hero-slider__c23": "theme-heading mt-1 font-mono text-[1.7rem]",
  "components-home-hero-slider__c24": "theme-image-frame relative mx-auto w-full max-w-[460px] overflow-hidden rounded-2xl p-1.5 shadow-[0_24px_54px_rgba(0,0,0,0.38)]",
  "components-home-hero-slider__c25": "relative aspect-[4/5] overflow-hidden rounded-[0.85rem]",
  "components-home-hero-slider__c26": "h-full w-full border-0",
  "components-home-hero-slider__c27": "object-cover",
  "components-home-hero-slider__c28": "absolute inset-0 bg-gradient-to-t from-slate-950/40 via-transparent to-purple-500/8",
  "components-home-hero-slider__c29": "relative z-10 mt-6 flex items-center justify-center gap-2",
  "components-home-hero-slider__c3": "pointer-events-none absolute -inset-8 opacity-45 [background-image:linear-gradient(98deg,transparent_0,transparent_13px,rgba(148,163,184,0.12)_14px,transparent_16px)] [background-size:28px_100%]",
  "components-home-hero-slider__c30": "h-2.5 rounded-full",
  "components-home-hero-slider__c31": "w-7 bg-purple-300",
  "components-home-hero-slider__c32": "w-2.5 bg-slate-500/70 hover:bg-slate-300/70",
  "components-home-hero-slider__c4": "pointer-events-none absolute -left-16 top-12 h-48 w-48 rounded-full bg-purple-400/12 blur-3xl",
  "components-home-hero-slider__c5": "pointer-events-none absolute -right-16 bottom-6 h-52 w-52 rounded-full bg-purple-300/12 blur-3xl",
  "components-home-hero-slider__c6": "relative z-10 grid min-h-[520px] gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-center",
  "components-home-hero-slider__c7": "space-y-6",
  "components-home-hero-slider__c8": "theme-chip rounded-sm px-3 py-1 text-xs font-semibold tracking-[0.24em]",
  "components-home-hero-slider__c9": "theme-heading max-w-4xl text-4xl font-black leading-[1.05] sm:text-6xl",
  "components-home-premium-gpu-grid__c1": "h-full",
  "components-home-premium-gpu-grid__c10": "theme-muted mt-2 text-sm",
  "components-home-premium-gpu-grid__c11": "mt-4 grid grid-cols-2 gap-2 text-[11px] text-zinc-400",
  "components-home-premium-gpu-grid__c12": "data-strip",
  "components-home-premium-gpu-grid__c13": "data-strip",
  "components-home-premium-gpu-grid__c14": "premium-btn premium-btn-ghost premium-control mt-4 inline-flex items-center px-4 py-2.5 text-sm",
  "components-home-premium-gpu-grid__c15": "grid gap-5 md:grid-cols-3",
  "components-home-premium-gpu-grid__c16": "h-full",
  "components-home-premium-gpu-grid__c2": "group relative h-full overflow-hidden border border-purple-500/45 bg-gradient-to-br from-slate-900/95 to-slate-800/80 p-5 shadow-[0_24px_56px_rgba(0,0,0,0.38)]",
  "components-home-premium-gpu-grid__c3": "pointer-events-none absolute inset-0",
  "components-home-premium-gpu-grid__c4": "theme-image-frame relative h-44 overflow-hidden",
  "components-home-premium-gpu-grid__c5": "object-cover",
  "components-home-premium-gpu-grid__c6": "absolute inset-0",
  "components-home-premium-gpu-grid__c7": "mt-4 flex items-center justify-between gap-3",
  "components-home-premium-gpu-grid__c8": "theme-heading text-xl font-bold",
  "components-home-premium-gpu-grid__c9": "font-mono text-xs tracking-[0.2em] text-purple-300",
  "components-home-premium-hero__c1": "premium-hero-shell group relative overflow-hidden p-7 sm:p-11",
  "components-home-premium-hero__c10": "premium-btn premium-btn-primary premium-control px-6 py-3 text-white",
  "components-home-premium-hero__c11": "premium-btn premium-btn-secondary premium-control px-6 py-3",
  "components-home-premium-hero__c12": "mt-10 grid gap-3 sm:grid-cols-3",
  "components-home-premium-hero__c13": "data-strip theme-metric",
  "components-home-premium-hero__c14": "theme-muted text-xs tracking-[0.2em]",
  "components-home-premium-hero__c15": "theme-heading mt-1 font-mono text-lg",
  "components-home-premium-hero__c16": "data-strip theme-metric",
  "components-home-premium-hero__c17": "theme-muted text-xs tracking-[0.2em]",
  "components-home-premium-hero__c18": "theme-heading mt-1 font-mono text-lg",
  "components-home-premium-hero__c19": "data-strip theme-metric",
  "components-home-premium-hero__c2": "premium-energy-gradient absolute -inset-28",
  "components-home-premium-hero__c20": "theme-muted text-xs tracking-[0.2em]",
  "components-home-premium-hero__c21": "theme-heading mt-1 font-mono text-lg",
  "components-home-premium-hero__c22": "theme-image-frame relative mx-auto w-full max-w-[460px] overflow-hidden rounded-2xl border-[0.5px] p-1.5 shadow-[0_20px_44px_rgba(0,0,0,0.32)]",
  "components-home-premium-hero__c23": "relative aspect-[4/5] overflow-hidden rounded-[0.9rem]",
  "components-home-premium-hero__c24": "object-cover",
  "components-home-premium-hero__c25": "absolute inset-0 bg-gradient-to-t from-slate-950/55 via-transparent to-purple-500/10",
  "components-home-premium-hero__c3": "premium-energy-lines absolute inset-0",
  "components-home-premium-hero__c4": "pointer-events-none absolute -translate-x-1/2 -translate-y-1/2 rounded-full bg-purple-300/28 blur-[70px]",
  "components-home-premium-hero__c5": "relative z-10 grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-center",
  "components-home-premium-hero__c6": "theme-chip mb-4 px-3 py-1 text-xs font-semibold tracking-[0.26em]",
  "components-home-premium-hero__c7": "theme-heading max-w-4xl text-4xl font-black tracking-tight sm:text-6xl",
  "components-home-premium-hero__c8": "theme-muted mt-6 max-w-2xl text-base sm:text-lg",
  "components-home-premium-hero__c9": "mt-7 flex flex-wrap gap-3",
  "components-layout-footer__c1": "mt-24 border-t border-purple-500/35 bg-slate-950/70 py-10",
  "components-layout-footer__c2": "flex flex-col gap-4 text-sm text-zinc-400 sm:flex-row sm:items-center sm:justify-between",
  "components-layout-footer__c3": "flex items-center gap-4",
  "components-layout-footer__c4": "premium-control hover:text-purple-300",
  "components-layout-footer__c5": "premium-control hover:text-purple-300",
  "components-layout-footer__c6": "premium-control hover:text-purple-300",
  "components-layout-mobile-nav__c1": "md:hidden",
  "components-layout-mobile-nav__c10": "",
  "components-layout-mobile-nav__c11": "opacity-0",
  "components-layout-mobile-nav__c12": "-translate-y-2 -rotate-45",
  "components-layout-mobile-nav__c13": "absolute left-0 right-0 top-[4.5rem] z-40 origin-top border-b border-purple-500/45 bg-slate-950/95 px-5 py-4 backdrop-blur transition",
  "components-layout-mobile-nav__c14": "scale-y-100 opacity-100",
  "components-layout-mobile-nav__c15": "pointer-events-none scale-y-0 opacity-0",
  "components-layout-mobile-nav__c2": "flex h-10 w-10 items-center justify-center border border-purple-500/60 bg-slate-900 text-zinc-300",
  "components-layout-mobile-nav__c3": "sr-only",
  "components-layout-mobile-nav__c4": "space-y-1.5",
  "components-layout-mobile-nav__c5": "space-y-3",
  "components-layout-mobile-nav__c6": "block rounded-lg px-3 py-2 text-sm font-semibold text-zinc-300 hover:bg-purple-950/40",
  "components-layout-mobile-nav__c7": "premium-btn premium-btn-primary premium-control block text-center text-sm text-white",
  "components-layout-mobile-nav__c8": "block h-0.5 w-5 bg-slate-100 transition",
  "components-layout-mobile-nav__c9": "translate-y-2 rotate-45",
  "components-layout-navbar__c1": "sticky top-0 z-30 border-b border-purple-500/40 bg-slate-950/70 backdrop-blur-xl motion-rise",
  "components-layout-navbar__c2": "flex h-[4.5rem] items-center justify-between",
  "components-layout-navbar__c3": "font-mono text-xl font-black tracking-[0.08em] text-white",
  "components-layout-navbar__c4": "hidden items-center gap-5 text-sm font-medium text-zinc-400 md:flex",
  "components-layout-navbar__c5": "premium-control transition hover:text-purple-300",
  "components-layout-navbar__c6": "hidden items-center gap-3 md:flex",
  "components-layout-navbar__c7": "premium-btn premium-btn-secondary premium-control",
  "components-layout-navbar__c8": "premium-btn premium-btn-primary premium-control text-white",
  "components-layout-sign-out-button__c1": "premium-btn premium-btn-secondary premium-control text-sm",
  "components-ui-container__c1": "mx-auto w-full max-w-[1180px] px-4 sm:px-6 lg:px-10",
  "components-ui-glass-card__c1": "surface-panel p-6",
  "components-ui-pagination-links__c1": "surface-rail flex items-center justify-between gap-3 p-4",
  "components-ui-pagination-links__c2": "text-sm text-zinc-400",
  "components-ui-pagination-links__c3": "premium-btn premium-control px-4 py-2 text-sm",
  "components-ui-pagination-links__c4": "pointer-events-none border-purple-600/60 bg-[#1a1a1a] text-zinc-500",
  "components-ui-pagination-links__c5": "premium-btn-secondary",
  "components-ui-section-title__c1": "space-y-4",
  "components-ui-section-title__c2": "theme-chip px-3 py-1 text-[11px] font-semibold tracking-[0.24em]",
  "components-ui-section-title__c3": "theme-heading max-w-3xl text-3xl font-bold tracking-tight sm:text-5xl",
  "components-ui-section-title__c4": "theme-muted max-w-2xl"
};
